name: "Formatting queries"
on: # rebuild any PRs and master branch changes
    pull_request:
    push:
        branches:
            - main
            
jobs:
  reformat-sql:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code so we have some files to look at.
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      # Run the reformat action
      - name: Reformat SQL Files
        uses: credfeto/action-sql-format@v1.3.1
      - name: Commit files
        run: |
          git config --local user.email "abhinit21@users.noreply.github.com"
          git config --local user.name "SQL Reformat Bot"
          git commit --all -m"Reformat SQL Files to common format." || true
      - name: Push
        run: git push "https://${{github.actor}}:${{secrets.SOURCE_PUSH_TOKEN}}@github.com/${{github.repository}}.git" "main:${{ env.GIT_BRANCH }}"
